"""added few new fields in User Model

Revision ID: 957d6cf0811c
Revises: 1b1483822a6f
Create Date: 2025-03-24 02:33:04.222593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957d6cf0811c'
down_revision = '1b1483822a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('middle_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('primary_phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('secondary_phone_number', sa.String(length=15), nullable=True))
        batch_op.create_unique_constraint(None, ['secondary_phone_number'])
        batch_op.create_unique_constraint(None, ['primary_phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('secondary_phone_number')
        batch_op.drop_column('primary_phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('middle_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
